icon: mdi:api
navigation.icon: mdi:api
title: WebSocket Server
description: Real-time interaction with Streamer.bot via the built-in WebSocket server.
ogImage:
  props:
    headline: API // WebSocket Server
