title: Guide
description: A comprehensive guide to configuring Streamer.bot, including Actions, Triggers, Variables, and more.
icon: mdi:book-open-page-variant-outline
navigation.icon: mdi:book-open-page-variant-outline
