title: Streamfog
icon: IconStreamfog
version: 1.0.7
aside.level: 4
category.title: Streamfog Sub-Actions
category.icon: IconStreamfog
navigation.title: Streamfog
navigation.description: Control Streamfog with Streamer.bot