title: Core Features
description: Learn about the core features of Streamer.bot, including Actions, Triggers, Variables, and more.
icon: "mdi:cube-scan"
navigation:
  title: Core Features
  icon: "mdi:cube-scan"
