title: Integrations
description: Integrate Streamer.bot with a variety of third-party services and tools, including Discord, IFTTT, Ko-Fi, and many more
navigation:
  title: Integrations
  icon: "mdi:puzzle"
